version: '3.4'

services:
  aleff.pizzaria.api:
    image: ${DOCKER_REGISTRY-}aleffpizzariaapi
    build:
      context: .
      dockerfile: Aleff.Pizzaria.Api/Dockerfile
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "P4sw0rdStrong159456"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"